<a href="https://colab.research.google.com/github/rkfussell/Physics_Affinity/blob/main/physicsAff_useful.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Set up**

This code section imports necessary packages and the data from Google Drive.

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import re

import pandas as pd
import numpy as np
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForCausalLM
from huggingface_hub import login
login()

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)


confidence = pd.read_excel("/content/drive/My Drive/Colab Notebooks/2024_fall_Cornell_Phys1101and2207_physaff_Rnd2_CollectiveCoding.xlsx",sheet_name="Confidence")
interest = pd.read_excel("/content/drive/My Drive/Colab Notebooks/2024_fall_Cornell_Phys1101and2207_physaff_Rnd2_CollectiveCoding.xlsx",sheet_name="Interest & Use")
confidence_codebook = pd.read_excel("/content/drive/My Drive/Colab Notebooks/2024_fall_Cornell_Phys1101and2207_physaff_Rnd2_CollectiveCoding.xlsx",sheet_name="Codebook-Confidence")
interest_codebook = pd.read_excel("/content/drive/My Drive/Colab Notebooks/2024_fall_Cornell_Phys1101and2207_physaff_Rnd2_CollectiveCoding.xlsx",sheet_name="Codebook-InterestandUse")

Mounted at /content/drive

**Run this cell to view the data that has been loaded in.**

In [ ]:
interest.head()

,Unnamed: 0,course,studentID,In a few (short) sentences: Do you expect to find learning\nphysics to be interesting and useful? Why or why not?,Interesting,Not interesting,Useful,Not Useful,Enjoyable,Applicable in Bio,...,math,how/why things work,daily life,essential knowledge,ability,required/MCAT,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,PHYS 2207,85ef67d0-649f-4e26-9545-1382bd4086a3,"I expect learning physics to be useful, but no...",NaN,x,x,NaN,NaN,NaN,...,x,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,PHYS 2207,2d8769ee-10f4-4635-8a2e-f8e6af40abd3,"I expect physics to be interesting, because I ...",x,NaN,x,NaN,x,NaN,...,NaN,x,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,PHYS 2207,b6b37f0b-dad5-4d8c-acbe-4a72a693eb6e,I think physics is both interesting and useful...,x,NaN,x,NaN,NaN,x,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,PHYS 2207,f8f33e36-9c73-4007-a43b-3fcf1122f2ab,I do not expect learning physics to be interes...,NaN,x,NaN,x,NaN,NaN,...,NaN,x,NaN,NaN,NaN,NaN,not enjoyable,NaN,NaN,NaN
4,NaN,PHYS 2207,dbb358dd-c4e8-4714-84d9-a32e477edfd8,I think it will be interesting but I do not th...,x,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**This line changes the question text to ``questionStem`` which we can use as a variable to identify the right column later.**

In [ ]:

interest = interest.rename(columns={"In a few (short) sentences: Do you expect to find learning\nphysics to be interesting and useful? Why or why not?":"questionStem"})
interest = interest.fillna(0)
interest = interest.replace('x',1)

/tmp/ipykernel_3620/2372801374.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  interest = interest.replace('x',1)

In [ ]:
interest

,Unnamed: 0,course,studentID,questionStem,Interesting,Not interesting,Useful,Not Useful,Enjoyable,Applicable in Bio,...,math,how/why things work,daily life,essential knowledge,ability,required/MCAT,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,0.0,PHYS 2207,85ef67d0-649f-4e26-9545-1382bd4086a3,"I expect learning physics to be useful, but no...",0,1,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0.0
1,0.0,PHYS 2207,2d8769ee-10f4-4635-8a2e-f8e6af40abd3,"I expect physics to be interesting, because I ...",1,0,1,0,1,0,...,0,1,0,0,0,0,0,0,0,0.0
2,0.0,PHYS 2207,b6b37f0b-dad5-4d8c-acbe-4a72a693eb6e,I think physics is both interesting and useful...,1,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0.0
3,0.0,PHYS 2207,f8f33e36-9c73-4007-a43b-3fcf1122f2ab,I do not expect learning physics to be interes...,0,1,0,1,0,0,...,0,1,0,0,0,0,not enjoyable,0,0,0.0
4,0.0,PHYS 2207,dbb358dd-c4e8-4714-84d9-a32e477edfd8,I think it will be interesting but I do not th...,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
667,0.0,PHYS 2207,d919df7f-ae2e-486f-b563-8d7780fbc994,I guess the parts of physics where I can easil...,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
668,0.0,PHYS 2207,b4e7cbfc-8d41-4e31-b841-89b8dbf1d0ba,I think it will be since it can be applied to ...,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
669,0.0,PHYS 1101,35f501b0-2ac2-4666-bd69-aa71af516978,"Yes, I want to do biotech so I think it will c...",0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
670,0.0,PHYS 1101,882ec822-d244-482f-9fea-b2abba2f1643,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0
671,0.0,PHYS 1101,d930c69c-7918-478e-89cf-63ff7e9f7276,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0.0

In [ ]:
#load model
model_name = "google/gemma-3-4b-it"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    output_hidden_states=True,
    dtype=torch.float32,
    device_map="auto"
)

config.json:   0%|          | 0.00/855 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/90.6k [00:00<?, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['output_hidden_states']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

Loading weights:   0%|          | 0/883 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

## **Prompt Set Up**

In this section, we'll define our prompt and the subsets of data we want to use to test it.**bold text**

In [ ]:

prompt = "Help me analyze some student statements. In each statement, decide if the student says physics is Useful, Not Useful, or you Can't Tell. If the student statement does not include the word ``useful'', categorize it as Can't Tell. Here are some examples:"

prompt+= "\n \n Example 1: ``I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.''"

prompt+= "\n Answer: **Useful** \n Explanation: The student says 'I expect learning physics to be useful', which is a positive statement about its use."

prompt+= "\n \n Example 2: ``I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting.''"

prompt+= "\n Answer: **Not Useful** \n Explanation: The student says they ``don't expect to find it useful', which is a negative statement about its use."

prompt+= "\n \n Example 3: ``Yes, I think that physics is important to learn however I'm not sure if it will be interesting. I hope it is.''"

prompt+= "\n Answer: **Can't Tell** \n Explanation: The student does not say the word ``useful'' so we can't tell what they think about its use."

prompt+= "\n \n Example 4: I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.''"

prompt+= "\n Answer: **Can't Tell** \n Explanation: The student says they are ``not sure'' which is not a positive nor a negative statement about its use."

prompt+= "\n \n Example 5: ``Not really; I have never been good at it.''"

prompt+= "\n Answer: **Can't Tell** \n Explanation: The student talks about their ability to do physics, not its use."

prompt+= "\n \n Here is another student statement. Tell me if the student says physics is Useful, physics is Not Useful, or you Can't Tell. Provide your answer first and then explain your reasoning. \n"

**Define subsets of the coded data so we can quickly check if Gemma has coded correctly.**

In [ ]:
useful = interest.loc[interest["Useful"] == 1]
notUseful = interest.loc[interest["Not Useful"] == 1]
cantTell = interest.loc[(interest["Useful"] == 0) & (interest["Not Useful"] == 0)]

## **Testing: Useful**

This code applies the prompt just to the useful subset, so we want Gemma to code everything as ``useful``.

In [ ]:
promptWithStatement=prompt + "``" + useful.iloc[3]['questionStem'] + "''"
print(promptWithStatement)

Help me analyze some student statements. In each statement, decide if the student says physics is Useful, Not Useful, or you Can't Tell. If the student doesn't talk about use explicitly, code it as Can't Tell. Here are some examples:

 Example 1: ``I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.''
 Answer: **Useful**
 Explanation: The student says 'I expect learning physics to be useful', which is a positive statement about its use.

 Example 2: ``I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting''
 Answer: **Not Useful**
 Explanation: Even though the student says they find physics interesting, they also say they don't expect to find it useful', which is a negative statement about its use.

 Example 3: ``Yes, I think that physics is important to learn however I'm not sure if it will be interesting. I hope it is.''
 Answer: **Can't Tell**
 Explanation: The student does not explicitly speak negatively or positively about its use.

 Here is another student statement. Tell me if the student says physics is Useful, physics is Not Useful, or you Can't Tell. Provide your answer first and then explain your reasoning.
``Learning physics will be useful to me. I am sure that understanding physics concepts will help me get insights about biological systems,  where passion and interests are.''

In [ ]:
base=prompt

count_useful, count_notUseful, count_noCode, count_fuckinGemma =0,0,0,0
with torch.no_grad():
  for i in range(0,144):

      promptWithStatement=base + "``" + useful.iloc[i]['questionStem'] + "''"
      inputs = tokenizer(promptWithStatement, return_tensors="pt").to(model.device)
      # Run inference
      outputs = model.generate(**inputs, max_new_tokens=10)
      # Decode the generated response
      ans = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
      # Define the first bit to get just Gemma's categorization
      ans_split = ans.split(useful.iloc[i]['questionStem'])[-1]
      gemmasFeelings = re.findall(r'\*\*(.*?)\*\*',ans_split)

      print("\n")
      print(i)
      # print("The full output is:")
      # print(ans)
      print("The sentence was: ")
      print(useful.iloc[i]['questionStem'])

      if len(gemmasFeelings) == 0:
          count_fuckinGemma+=1
          print("Gemma feels that it is: ")
          print(ans_split)
          continue
      else:
          print("The stripped answer is: ")
          print(gemmasFeelings[0])

      # print("Gemma's feelings 1st element: ")
      # print(gemmasFeelings[0])

      if "Useful" == gemmasFeelings[0]:
          count_useful+=1
      elif "Not Useful" == gemmasFeelings[0]:
          count_notUseful+=1
      elif "Can't Tell" == gemmasFeelings[0]:
          count_noCode+=1
      else:
          print("The sentence was: ")
          print(useful.iloc[i]['questionStem'])
          print("Gemma feels that it is: ")
          print(ans_split)

print(count_useful)
print(count_notUseful)
print(count_noCode)
print(count_fuckinGemma)

0
The sentence was:
I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas
The stripped answer is:
Useful


1
The sentence was:
I expect physics to be interesting, because I like to learn about how we can predict trajectories of a ball and perform physics labs. I think it will be very useful to better understanding our environment and how the world works.
The stripped answer is:
Useful


2
The sentence was:
I think physics is both interesting and useful. It is very applicable to the real world in the healthcare sector particularly. If also provides explanation for certain biological processes.
The stripped answer is:
Useful


3
The sentence was:
Learning physics will be useful to me. I am sure that understanding physics concepts will help me get insights about biological systems,  where passion and interests are.
The stripped answer is:
Useful


4
The sentence was:
Physics is the foundation of all other sciences: chemistry, biology, etc. In other words, everything involves physics. In this way, physics is useful to me as a future physician.
The stripped answer is:
Useful


5
The sentence was:
Yes, I do. From the little that I reviewed over the summer, the content and concepts in physics seem interesting and useful within the context of daily life and medicine (eg. the use of laparoscopic instruments in surgery).
The stripped answer is:
Useful


6
The sentence was:
I think learning physics will be difficult, but also useful because it'll help me understand and connect physics to other parts of my interests.
The stripped answer is:
Useful


7
The sentence was:
I expect to find it somewhat useful and somewhat interesting. In my particular career path I don't expect it to be very useful, however I believe a basic understanding of physics will be useful in my life in general. There are some aspects of physics that interest me, although in high school I was turned off by some challenging problems.
The stripped answer is:
Useful


8
The sentence was:
I know physics is applicable in many parts of life and biology, so I expect it will be useful, although at this point I don't know exactly what that will look like. I also don't know how interesting it will be.
The stripped answer is:
Useful


9
The sentence was:
I expect it to be demanding and useful for completing my pre-med course requirements.
The stripped answer is:
Useful


10
The sentence was:
I find learning physics to be useful as it has a connection to many real life phenomena such as sports, driving, and medicine. Moreover, I am excited to learn physics concepts that will help me in the medical world in terms of understanding the physiology of the human body.
The stripped answer is:
Useful


11
The sentence was:
Yes, both interesting and useful. I think I ask myself a lot of questions about the biological world around me that I can imagine physics may help me further my understanding. I'm excited to be able to address some of those questions with a bit more scientific insight. I think it will be interesting because it's an untouched subject area to me.
The stripped answer is:
Useful


12
The sentence was:
I expect it to be interesting, and relatively useful. I'm not sure if I'll use it in the future, but I think physics is very interesting.
The stripped answer is:
Useful


13
The sentence was:
I expect physics to be useful for the rest of my undergraduate and graduate studies. I know that physics is heavily featured on the MCAT and this course will help me prepare. In the past, I did not find physics very interesting, but I am hoping this changes!!
The stripped answer is:
Useful


14
The sentence was:
I do find learning physics to be both interesting and useful for both my own understanding of the world around me as well as for future studies as I pursue medicine. I personally believe that concepts in physics retain longer and are harder to forget than concepts in say chemistry for example.
The stripped answer is:
Useful


15
The sentence was:
I personally do not as I will likely never do it again after the class. I think basics physics is useful but nothing more than extremely basic ideas since so much relies heavily on math which most people do not learn. But I would say this about alot of classes you have to take an university.
The stripped answer is:
Not Useful


16
The sentence was:
I expect that some of the information will be very useful to me in the field of medicine. I think that a lot of biomedical devices and technology are based in physics. I do thing that some of the things I am learning may not be as useful such as the electromagnitism, however I have not learned this before so maybe it will be useful.
The stripped answer is:
Useful


17
The sentence was:
I expect to find it somewhat interesting and useful. I have taken physics before and know I will not use everything I will learn. However, some topics are helpful when thinking about the world. I also find most STEM topics engaging and expect to find physics stimulating to me as someone who likes math and science.
The stripped answer is:
Useful


18
The sentence was:
I feel that learning physics will be interesting and useful. The concepts that we will learn in physics can be applied to daily life! So I think solving physics problems will be applicable in the real world.
The stripped answer is:
Useful


19
The sentence was:
Yes physics will be interesting and useful in the real world because everything we do in life uses physics application. Learning physics will help me make those connections in life when I look at a cool architecture and start thinking about how it was built.
The stripped answer is:
Useful


20
The sentence was:
I do not expect to find learning physics to be interesting. I used to expect it in high school and I faced a disillusionment. I do expect learning physics to be very useful even though it is extremely confusing and tedious.
The stripped answer is:
Useful


21
The sentence was:
I think it will be useful and interesting! My brother is a physics major, and his interest in it piqued mine.
The stripped answer is:
Useful


22
The sentence was:
I believe that learning physics will not be very interesting, but very useful. All science is basically physics, so understanding this foundation will help me apply myself in other difficult courses. However, physics is very hard to me, so it might not be as enjoyable as I hope it to be.
The stripped answer is:
Useful


23
The sentence was:
Yes definitely, everything in this world can be explained by physics, especially movement. Since it can be applied in so many ways, it's hard to argue that it isn't useful.
The stripped answer is:
Useful


24
The sentence was:
I definitely think it will be interesting because I am naturally very curious and because of my desired career path I think it would 100% be useful.
The stripped answer is:
Useful


25
The sentence was:
I expect to find physics moderately interesting and useful. I have never been good at physics, so I dont think i have an inclination to find it interesting like other students.
The stripped answer is:
Useful


26
The sentence was:
I study architecture and I think some concepts in physics would be very useful when it comes to architecture.
The stripped answer is:
Useful


27
The sentence was:
I expect physics to be useful as it can be seen in everyday life. I think this will help to make the content more interesting. Moreover, I hope to see its applications in my major.
The stripped answer is:
Useful


28
The sentence was:
I find some topics in physics to be interesting and I know that all the topics are universally useful. I find the topics that I am constantly surrounded with and am reminded of to be interesting because you never really notice it until you learn about it.
The stripped answer is:
Useful


29
The sentence was:
Yes, I expect to find it interesting and useful. This is because physics is a field of science where we can see its mechanisms in the real world, so learning about it wouldn't just be about theoretical ideas.
The stripped answer is:
Useful


30
The sentence was:
I can't guarantee it must be interesting, but I think it will surely be useful, as the microscopic part is highly associated with chemistry (e.g.electrons, protons, Œ± and Œ≤ particles)
The stripped answer is:
Useful


31
The sentence was:
I really do expect it to be interesting and useful. I am a very curious person and am interested to learn about applications toward the real world. I also am curious to see how I can use physics to learn more about human biology, my major.
The stripped answer is:
Useful


32
The sentence was:
I do think physics will be interesting and useful. I like problem solving with numbers which is essentially what physics is and there are applications in everything.
The stripped answer is:
Useful


33
The sentence was:
I do expect it to be interesting. I think I will find labs to be more interesting than practice problems. I think it is useful to apply to the real world and that it can teach you important concepts to think about in everyday life.
The stripped answer is:
Useful


34
The sentence was:
I think I will find it interesting and useful to apply in certain aspects of my life. It might be hard now to rationalize the ways physics impacts the world, but I believe there are probably underlying principles of physics in our everyday lives.
The stripped answer is:
Useful


35
The sentence was:
Yes, I expect physics to be interesting and useful because it is an essential science that everyone should have a foundational understanding of. Also, it helps with problem solving and that is a key skill to acquire for academics.
The stripped answer is:
Useful


36
The sentence was:
Yes, I hope to pursue a research career, and I know having at the very least an introductory background in physics can be very helpful for part of that career.
Gemma feels that it is:
''
 Answer:
 Explanation:



37
The sentence was:
I expect physics to be interesting and useful. I have trouble keeping interest when physics problems get very hard, but the concepts themselves I find very interesting and makes me look at daily life through a different perspective.
The stripped answer is:
Useful


38
The sentence was:
I do expect to find learning physics interesting and useful. I had enjoyed it in high school and all sciences fascinate me, although I do not think it will become something I am passionate about. I think a year of learning it will make me respect/admire it much more.
The stripped answer is:
Useful


39
The sentence was:
I believe that learning physics will be both interesting and useful. Learning physics will be interesting because it is something so connected to everyday life! Investigating the laws behind why objects behave the way they do, in my eyes, is pretty cool. That being said, understanding the laws that explain why objects behave the way they do will also be useful to my everyday knowledge of why things are the way that they are, and I am confident the concepts that I learn in this physics course will be applied within my field of study.
Gemma feels that it is:
''
 Answer:
 Explanation:



40
The sentence was:
It is useful for everyday applications
The stripped answer is:
Useful


41
The sentence was:
Yes. I've always had a fascination with physics through nonfiction books and YouTube channels such as Veritasium. I hope to uncover a more thorough understanding of it through this course. I have a slight interest in astronomy and quantum physics. I know that mechanics will not be close to covering those concepts, but it will provide the foundation for those more advanced concepts. Again, this will help me with my career as a future physician, so it will definitely be useful to me.
The stripped answer is:
Useful


42
The sentence was:
I expect it to be a useful subject even if I am not necessarily interested in it.
The stripped answer is:
Useful


43
The sentence was:
Yes, I hope to find physics interesting and useful since I am a figure skater so inertia, torque, momentum all play important roles in the sport.
The stripped answer is:
Useful


44
The sentence was:
I currently do not think learning physics to be quite interesting but I definitely think it is useful. I need physics for my major and for several graduate exams later on so it is very useful to me. However, it is more math heavy compared to chemistry and biology so it is less interesting to me.
The stripped answer is:
Useful


45
The sentence was:
I expect learning physics to be interesting and useful. This is because it has many applications, such as in the human body and different physiological processes. Moreover, I love learning about how things work in our everyday lives. The ability to problem solve is something that I will improve upon in this course, which will be useful.
The stripped answer is:
Useful


46
The sentence was:
I have always found physics interesting and I think it will help me in my future academics.
The stripped answer is:
Useful


47
The sentence was:
I expect to find learning physics to be a bit difficult, but interesting and useful. I have learned physics indirectly from other courses, such as CHEM 2070 and BIOG 1440, and I have especially found those physics concepts very interesting, specifically in BIOG 1440 where we learned about the physics of blood flow and circulation. Additionally, physics is provides part of the foundation for lots of various biological processes in the body, which is something I hope to explore in the future in my career, and so the concepts I learn in physics will aid in my understanding of said processes.
The stripped answer is:
Useful


48
The sentence was:
I expect to find learning about physics useful because I'll be able to understand more about the general world I live in. I will understand more about complex topics that my friends are interested in.
The stripped answer is:
Useful


49
The sentence was:
I think learning physics will be useful as I am an engineering major. Physics is the basis for understanding critical engineering concepts. Physics can also be found in our day to day lives
The stripped answer is:
Useful


50
The sentence was:
I do, I have never taken a physics course but many of my friends say a basic understanding is a very useful skill.
The stripped answer is:
Useful


51
The sentence was:
Yes I do find learning physics to be interesting and useful. I find that it is one of the sciences that applies the most during the real world. We can see laws of physics happening in our everyday lives, so I do find it interesting to learn more about it.
The stripped answer is:
Useful


52
The sentence was:
I expect learning physics to be interesting and useful. I think that physics has a lot of relation to everyday life, and has a lot of overlap with other STEM and pre-med classes. A better of understanding of physics can help me in other classes and be a better problem-solver and thinker.
The stripped answer is:
Useful


53
The sentence was:
I do in fact find that learning physics is very useful. I plan on becoming a physician; therefore, these skills will be used often in the field.
The stripped answer is:
Useful


54
The sentence was:
I think it will be interesting. I always enjoy gaining a deeper understanding of the world through mathematical concepts. I think it will be useful for the MCAT.
The stripped answer is:
Useful


55
The sentence was:
I will expect physics to be useful but I think it will only be interesting if I find it easier to digest.
The stripped answer is:
Useful


56
The sentence was:
I think physics is useful and interesting. Understanding how things function is always important.
The stripped answer is:
Useful


57
The sentence was:
Yes, I expect to find learning physics both interesting and useful. The subject offers insights into the fundamental laws that govern the natural world, which is fascinating.
The stripped answer is:
Useful


58
The sentence was:
I think physics will be pretty interesting and useful. Physics explains objects and how they behave in the natural world and I feel like understanding these principles would allow me to further analyze and grasp concepts in both my career and in life as a whole.
The stripped answer is:
Useful


59
The sentence was:
Yes, I think it will be interesting because it will give me a better understanding of how the world works. I think it will be useful because physics plays a large role in anyone's life so learning more about it will help me with anything that involves physics.
The stripped answer is:
Useful


60
The sentence was:
It could be very interesting and useful since physics dictates the way this world works, so it will be cool to learn about the connections.
The stripped answer is:
Useful


61
The sentence was:
I do not expect learning physics to be interesting, but I do expect it to be somewhat useful. I did not like any physics that was taught in high school, but I have had to apply it in some other classes.
The stripped answer is:
Useful


62
The sentence was:
I do expect to find learning physics to be interesting--I know this is a general statement, but I want to be able to understand the mechanics behind how the world works. I definitely expect to find learning physics to be useful--I have to know it for the MCAT and also as an aspiring future physician.
The stripped answer is:
Useful


63
The sentence was:
I expect learning physics to be interesting and useful because its applications are very widespread and apparent to anyone who observes the world around them. I think it will be useful not only to my career, but to life in general.
The stripped answer is:
Useful


64
The sentence was:
I expect it to be interesting because of how apparent physics is around us. I feel it is always more interesting to be able to see actual properties/ideas we learn about us in the world around us. I also expect it to be useful because it governs everything that we do and the way things move/work.
The stripped answer is:
Useful


65
The sentence was:
I do expect learning physics to be interesting and useful. This is due to my background as a pre-dental student. Physics is utterly important in orthodontic procedures and treatment and am eager to be able to apply my knowledge from physics to my future career.
The stripped answer is:
Useful


66
The sentence was:
I expect to find it interesting because it will teach me how a lot of things work that I do not yet understand. I expect it to be useful in some parts of my life, but not all. I see its applications in my field (animal science) regarding thermodynamics and energy, but I do not yet see other relevance. Hopefully, I will learn more.
The stripped answer is:
Useful


67
The sentence was:
I expect physics to be useful because when i took physics 1, i saw it apply in almost everything in life and would often get excited when i saw something i know can be explained by physics.
The stripped answer is:
Useful


68
The sentence was:
I expect to find it useful, but not necessarily interesting. I don't necessarily do as well when physics is taught via just lecture, since I find the more physical applications more interesting and that would be through experiments. I like the ideas behind physics but i dont know if i necessarily find the content engaging.
The stripped answer is:
Useful


69
The sentence was:
I am not sure how interesting it will be, but I know that physics will be of use to me in the future. It will help me better grasp concepts that are a part of the field that I am passionate about (biology), such as blood flow and circulation. As the course proceeds, I might build an interest in physics.
The stripped answer is:
Useful


70
The sentence was:

## **Testing: Not Useful**

This code tests the not useful subset, again so we can make sure the prompt is working well.

In [ ]:
print(prompt)

Help me analyze some student statements. In each statement, decide if the student says physics is Useful, Not Useful, or you Can't Tell. If the student doesn't talk about use explicitly, code it as Can't Tell. Here are some examples:

 Example 1: ``I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.''
 Answer: **Useful**
 Explanation: The student says 'I expect learning physics to be useful', which is a positive statement about its use.

 Example 2: ``I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting''
 Answer: **Not Useful**
 Explanation: Even though the student says they find physics interesting, they also say they don't expect to find it useful', which is a negative statement about its use.

 Example 3: ``Yes, I think that physics is important to learn however I'm not sure if it will be interesting. I hope it is.''
 Answer: **Can't Tell**
 Explanation: The student does not explicitly speak negatively or positively about its use.

 Here is another student statement. Tell me if the student says physics is Useful, physics is Not Useful, or you Can't Tell. Provide your answer first and then explain your reasoning.

In [ ]:
base=prompt

count_useful, count_notUseful, count_noCode, count_fuckinGemma =0,0,0,0
with torch.no_grad():
  for i in range(0,17):

      promptWithStatement=base + "``" + notUseful.iloc[i]['questionStem'] + "''"
      inputs = tokenizer(promptWithStatement, return_tensors="pt").to(model.device)
      # Run inference
      outputs = model.generate(**inputs, max_new_tokens=20)
      # Decode the generated response
      ans = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
      # Define the first bit to get just Gemma's categorization
      ans_split = ans.split(notUseful.iloc[i]['questionStem'])[-1]
      gemmasFeelings = re.findall(r'\*\*(.*?)\*\*',ans_split)

      print("\n")
      print(i)
      # print("The full output is:")
      # print(ans)
      print("The sentence was: ")
      print(notUseful.iloc[i]['questionStem'])

      if len(gemmasFeelings) == 0:
          count_fuckinGemma+=1
          print("Gemma feels that it is: ")
          print(ans_split)
          continue
      else:
          print("The stripped answer is: ")
          print(gemmasFeelings[0])

      # print("Gemma's feelings 1st element: ")
      # print(gemmasFeelings[0])

      if "Useful" == gemmasFeelings[0]:
          count_useful+=1
      elif "Not Useful" == gemmasFeelings[0]:
          count_notUseful+=1
      elif "Can't Tell" == gemmasFeelings[0]:
          count_noCode+=1
      else:
          print("The sentence was: ")
          print(notUseful.iloc[i]['questionStem'])
          print("Gemma feels that it is: ")
          print(ans_split)

print(count_useful)
print(count_notUseful)
print(count_noCode)
print(count_fuckinGemma)

0
The sentence was:
I do not expect learning physics to be interesting and useful. I don't really understand the point of knowing a bunch of information about why/how things move, because it doesn't really pertain to my major. I also don't enjoy physics as a subject, so I don't see myself applying it in my life during/after the class.
The stripped answer is:
Not Useful


1
The sentence was:
I expect it to be interesting maybe not as useful. I want to be a surgeon and I don't think physics will come up a lot.
The stripped answer is:
Not Useful


2
The sentence was:
I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.
The stripped answer is:
Can't Tell


3
The sentence was:
I think it will be kind of interesting but not really useful because in this introductory course I doubt if I can learn anything really applicable in my biology study.
The stripped answer is:
Not Useful


4
The sentence was:
I don't necessarily expect it to be useful to what I want to do in the future. I mainly find water physics interesting because I am a swimmer, but otherwise not much of physics sounds interesting.
The stripped answer is:
Not Useful


5
The sentence was:
To be honest, I don't find physics very appealing. I was never very interested in it mainly because I don't think it will be useful for my future career. I plan to go on to medical school and become a surgeon. Although physics is required for this field, I don't see how physics can be used to help patients all that much. Despite this, I will keep an open mind throughout the course.
The stripped answer is:
Not Useful


6
The sentence was:
I expect it to be interesting. I do not expect it to be useful. Interesting because I am a fan of most sciences, not useful because I simply think another buisness or chemistry cource would be time better spent for my major, food science.
The stripped answer is:
Not Useful


7
The sentence was:
I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting
The stripped answer is:
Not Useful


8
The sentence was:
No, I expect to get overwhelmed which won't be of any use.
The stripped answer is:
Not Useful


9
The sentence was:
it can be interesting but since it is not applied probably not that useful in life, cause I am not going to be building stuff
The stripped answer is:
Not Useful


10
The sentence was:
I am planning on continuing on the pre-health track. Because there is not a major involvement of physics in that career path, I do not feel it would be particularly useful. I do, however, feel that physics is interesting as it explains many things from our everyday experiences.
The stripped answer is:
Not Useful


11
The sentence was:
I do not expect to find learning physics to be interesting or useful because it is not a field that I am typically drawn to and it involves a lot of math, which is not my strongsuit.
The stripped answer is:
Not Useful


12
The sentence was:
I think physics will be interesting to learn because it's literally how the world works and explains so many things. I think it's cool how we can't physically see physics in action with the naked eye, but it's effects are so huge. In terms of if it'll be useful in my career, I don't think it'll be that useful.
The stripped answer is:
Not Useful


13
The sentence was:
I do not expect to find learning physics all that useful just because I am pre med and am not entirely sure how much physics is used in the medical field.
The stripped answer is:
Not Useful


14
The sentence was:
I do expect it to be interesting, but probably not useful. I found physics enjoyable in high school, but I have been told it is not practically applicable to a further education in veterinary medicine.
The stripped answer is:
Not Useful


15
The sentence was:
I find it interesting, but I do not find it as useful for me specifically because of I want to become a Physician Assistant in the medical field where biology and chemistry are more applicable than physics.
The stripped answer is:
Not Useful


16
The sentence was:
I think learning physics will be interesting to me because physics is a very practical science and it present in any structure or problems that arises in every day life. I don't think physics will be very useful in my life and future career as I plan on working in an environment that is with people and communities.
The stripped answer is:
Useful
1
15
1
0

## **Testing: Can't Tell / Neither**

This code tests the not useful subset, again so we can make sure the prompt is working well.

In [ ]:
promptTakeTwo = "I asked students if they thought physics was interesting and/or useful. Help me analyze their responses to figure out which students think its USEFUL and how many think it is NOT USEFUL."
promptTakeTwo+= "\n For each student statement, first report if the student answers the question about USE."
promptTakeTwo+= "\n Only if the statement contains the word USE or USEFUL, decide if the student thinks physics is USEFUL, NOT USEFUL, or you CAN'T TELL."
promptTakeTwo+= "\n If the statement does not contain the word USE or USEFUL, you must label the statement as CAN'T TELL. Here are some examples:"

promptTakeTwo+= "\n \n Example 1: I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas."

promptTakeTwo+= "\n Answer: **USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a positive about its use."

promptTakeTwo+= "\n \n Example 2: I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting."

promptTakeTwo+= "\n Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a negative about its use."

promptTakeTwo+= "\n \n Example 3: Not really; I have never been good at it."

promptTakeTwo+= "\n Answer: **CAN'T TELL** Explanation: The statement does not contain the words ``USEFUL'' or ``USE''."

promptTakeTwo+= "\n \n Example 4: I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue."

promptTakeTwo+= "\n Answer: **CAN'T TELL** Explanation: The statement contains the word ``USEFUL'', but also says that the they are ``not sure'' which is not only positive or only negative."

promptTakeTwo+= "\n \n Here is another student statement. Tell me if the statement should be categorized as USEFUL, NOT USEFUL, or CAN'T TELL. Provide your answer first and then explain your reasoning. \n"

In [ ]:
print(promptTakeTwo)

I asked students if they thought physics was interesting and/or useful. Help me analyze their responses to figure out which students think its USEFUL and how many think it is NOT USEFUL.
 For each student statement, first report if the student answers the question about USE.
 Only if the statement contains the word USE or USEFUL, decide if the student thinks physics is USEFUL, NOT USEFUL, or you CAN'T TELL.
 If the statement does not contain the word USE or USEFUL, you must label the statement as CAN'T TELL. Here are some examples:

 Example 1: I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.
 Answer: **USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a positive about its use.

 Example 2: I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting.
 Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a negative about its use.

 Example 3: Not really; I have never been good at it.
 Answer: **CAN'T TELL** Explanation: The statement does not contain the words ``USEFUL'' or ``USE''.

 Example 4: I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.
 Answer: **CAN'T TELL** Explanation: The statement contains the word ``USEFUL'', but also says that the they are ``not sure'' which is not only positive or only negative.

 Here is another student statement. Tell me if the statement should be categorized as USEFUL, NOT USEFUL, or CAN'T TELL. Provide your answer first and then explain your reasoning.

In [ ]:
base=promptTakeTwo

count_useful, count_notUseful, count_noCode, count_fuckinGemma =0,0,0,0
with torch.no_grad():
  for i in range(0,15):

      promptWithStatement=base + "Statement: ``" + cantTell.iloc[i]['questionStem'] + "''"
      inputs = tokenizer(promptWithStatement, return_tensors="pt").to(model.device)
      # Run inference
      outputs = model.generate(**inputs, max_new_tokens=25)
      # Decode the generated response
      ans = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
      # Define the first bit to get just Gemma's categorization
      ans_split = ans.split(cantTell.iloc[i]['questionStem'])[-1]
      gemmasFeelings = re.findall(r'\*\*(.*?)\*\*',ans_split)

      print("\n")
      print(i)
      print("The full output is:")
      print(ans)
      # print("The sentence was: ")
      # print(cantTell.iloc[i]['questionStem'])

      if len(gemmasFeelings) == 0:
          count_fuckinGemma+=1
          print("Gemma feels that it is: ")
          print(ans_split)
          continue
      else:
          print("The stripped answer is: ")
          print(gemmasFeelings[0])

      # print("Gemma's feelings 1st element: ")
      # print(gemmasFeelings[0])

      if "USEFUL" == gemmasFeelings[0]:
          count_useful+=1
      elif "NOT USEFUL" == gemmasFeelings[0]:
          count_notUseful+=1
      elif "CAN'T TELL" == gemmasFeelings[0]:
          count_noCode+=1
      else:
          print("The sentence was: ")
          print(cantTell.iloc[i]['questionStem'])
          print("Gemma feels that it is: ")
          print(ans_split)

print(count_useful)
print(count_notUseful)
print(count_noCode)
print(count_fuckinGemma)

0
The full output is:
I asked students if they thought physics was interesting and/or useful. Help me analyze their responses to figure out which students think its USEFUL and how many think it is NOT USEFUL.
 For each student statement, first report if the student answers the question about USE.
 Only if the statement contains the word USE or USEFUL, decide if the student thinks physics is USEFUL, NOT USEFUL, or you CAN'T TELL.
 If the statement does not contain the word USE or USEFUL, you must label the statement as CAN'T TELL. Here are some examples:

 Example 1: I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.
 Answer: **USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a positive about its use.

 Example 2: I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting.
 Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a negative about its use.

 Example 3: Not really; I have never been good at it.
 Answer: **CAN'T TELL** Explanation: The statement does not contain the words ``USEFUL'' or ``USE''.

 Example 4: I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.
 Answer: **CAN'T TELL** Explanation: The statement contains the word ``USEFUL'', but also says that the they are ``not sure'' which is not only positive or only negative.

 Here is another student statement. Tell me if the statement should be categorized as USEFUL, NOT USEFUL, or CAN'T TELL. Provide your answer first and then explain your reasoning.
Statement: ``I think it will be interesting but I do not think it will come up often in my future career.''
Answer: **NOT USEFUL**
Explanation: The statement contains the word ``USEFUL'' and the student explicitly says
The stripped answer is:
NOT USEFUL


1
The full output is:
I asked students if they thought physics was interesting and/or useful. Help me analyze their responses to figure out which students think its USEFUL and how many think it is NOT USEFUL.
 For each student statement, first report if the student answers the question about USE.
 Only if the statement contains the word USE or USEFUL, decide if the student thinks physics is USEFUL, NOT USEFUL, or you CAN'T TELL.
 If the statement does not contain the word USE or USEFUL, you must label the statement as CAN'T TELL. Here are some examples:

 Example 1: I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.
 Answer: **USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a positive about its use.

 Example 2: I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting.
 Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a negative about its use.

 Example 3: Not really; I have never been good at it.
 Answer: **CAN'T TELL** Explanation: The statement does not contain the words ``USEFUL'' or ``USE''.

 Example 4: I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.
 Answer: **CAN'T TELL** Explanation: The statement contains the word ``USEFUL'', but also says that the they are ``not sure'' which is not only positive or only negative.

 Here is another student statement. Tell me if the statement should be categorized as USEFUL, NOT USEFUL, or CAN'T TELL. Provide your answer first and then explain your reasoning.
Statement: ``Yes, as in sports medicine for animals, looking at weight distribution is important and knowing certain biomechanics in terms of orthopedics ''
Answer: **USEFUL**
 Explanation: The statement contains the word "USEFUL" and expresses a specific example
The stripped answer is:
USEFUL


2
The full output is:
I asked students if they thought physics was interesting and/or useful. Help me analyze their responses to figure out which students think its USEFUL and how many think it is NOT USEFUL.
 For each student statement, first report if the student answers the question about USE.
 Only if the statement contains the word USE or USEFUL, decide if the student thinks physics is USEFUL, NOT USEFUL, or you CAN'T TELL.
 If the statement does not contain the word USE or USEFUL, you must label the statement as CAN'T TELL. Here are some examples:

 Example 1: I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.
 Answer: **USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a positive about its use.

 Example 2: I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting.
 Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a negative about its use.

 Example 3: Not really; I have never been good at it.
 Answer: **CAN'T TELL** Explanation: The statement does not contain the words ``USEFUL'' or ``USE''.

 Example 4: I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.
 Answer: **CAN'T TELL** Explanation: The statement contains the word ``USEFUL'', but also says that the they are ``not sure'' which is not only positive or only negative.

 Here is another student statement. Tell me if the statement should be categorized as USEFUL, NOT USEFUL, or CAN'T TELL. Provide your answer first and then explain your reasoning.
Statement: ``Yes. I think topics such as fluid dynamics and heat transfer are very important in both daily life and in scientific research. ''
Answer: **USEFUL**
Explanation: The statement contains the word ``USEFUL'' and the student is positive
The stripped answer is:
USEFUL


3
The full output is:
I asked students if they thought physics was interesting and/or useful. Help me analyze their responses to figure out which students think its USEFUL and how many think it is NOT USEFUL.
 For each student statement, first report if the student answers the question about USE.
 Only if the statement contains the word USE or USEFUL, decide if the student thinks physics is USEFUL, NOT USEFUL, or you CAN'T TELL.
 If the statement does not contain the word USE or USEFUL, you must label the statement as CAN'T TELL. Here are some examples:

 Example 1: I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.
 Answer: **USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a positive about its use.

 Example 2: I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting.
 Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a negative about its use.

 Example 3: Not really; I have never been good at it.
 Answer: **CAN'T TELL** Explanation: The statement does not contain the words ``USEFUL'' or ``USE''.

 Example 4: I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.
 Answer: **CAN'T TELL** Explanation: The statement contains the word ``USEFUL'', but also says that the they are ``not sure'' which is not only positive or only negative.

 Here is another student statement. Tell me if the statement should be categorized as USEFUL, NOT USEFUL, or CAN'T TELL. Provide your answer first and then explain your reasoning.
Statement: ``I think physics is interesting because it governs a lot of things in my everyday life. I don't know what situations I would apply my knowledge in, though.''
Answer: **CAN'T TELL**
Explanation: The statement contains the word “USEFUL” but the student expresses
The stripped answer is:
CAN'T TELL


4
The full output is:
I asked students if they thought physics was interesting and/or useful. Help me analyze their responses to figure out which students think its USEFUL and how many think it is NOT USEFUL.
 For each student statement, first report if the student answers the question about USE.
 Only if the statement contains the word USE or USEFUL, decide if the student thinks physics is USEFUL, NOT USEFUL, or you CAN'T TELL.
 If the statement does not contain the word USE or USEFUL, you must label the statement as CAN'T TELL. Here are some examples:

 Example 1: I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.
 Answer: **USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a positive about its use.

 Example 2: I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting.
 Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a negative about its use.

 Example 3: Not really; I have never been good at it.
 Answer: **CAN'T TELL** Explanation: The statement does not contain the words ``USEFUL'' or ``USE''.

 Example 4: I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.
 Answer: **CAN'T TELL** Explanation: The statement contains the word ``USEFUL'', but also says that the they are ``not sure'' which is not only positive or only negative.

 Here is another student statement. Tell me if the statement should be categorized as USEFUL, NOT USEFUL, or CAN'T TELL. Provide your answer first and then explain your reasoning.
Statement: ``I feel as though physics is very important for those who wish to understand the world around them, and when combined with other fields, explains many phenomena ''

 Answer: **USEFUL**
 Explanation: The statement contains the word ``USEFUL'' and the student states
The stripped answer is:
USEFUL


5
The full output is:
I asked students if they thought physics was interesting and/or useful. Help me analyze their responses to figure out which students think its USEFUL and how many think it is NOT USEFUL.
 For each student statement, first report if the student answers the question about USE.
 Only if the statement contains the word USE or USEFUL, decide if the student thinks physics is USEFUL, NOT USEFUL, or you CAN'T TELL.
 If the statement does not contain the word USE or USEFUL, you must label the statement as CAN'T TELL. Here are some examples:

 Example 1: I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.
 Answer: **USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a positive about its use.

 Example 2: I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting.
 Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a negative about its use.

 Example 3: Not really; I have never been good at it.
 Answer: **CAN'T TELL** Explanation: The statement does not contain the words ``USEFUL'' or ``USE''.

 Example 4: I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.
 Answer: **CAN'T TELL** Explanation: The statement contains the word ``USEFUL'', but also says that the they are ``not sure'' which is not only positive or only negative.

 Here is another student statement. Tell me if the statement should be categorized as USEFUL, NOT USEFUL, or CAN'T TELL. Provide your answer first and then explain your reasoning.
Statement: ``A little bit. I like noticing it in my everyday life. However, I don't expect it to be my strong suit. ''
Answer: **CAN'T TELL**
Explanation: The statement contains the word "USEFUL", but it also contains
The stripped answer is:
CAN'T TELL


6
The full output is:
I asked students if they thought physics was interesting and/or useful. Help me analyze their responses to figure out which students think its USEFUL and how many think it is NOT USEFUL.
 For each student statement, first report if the student answers the question about USE.
 Only if the statement contains the word USE or USEFUL, decide if the student thinks physics is USEFUL, NOT USEFUL, or you CAN'T TELL.
 If the statement does not contain the word USE or USEFUL, you must label the statement as CAN'T TELL. Here are some examples:

 Example 1: I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.
 Answer: **USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a positive about its use.

 Example 2: I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting.
 Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a negative about its use.

 Example 3: Not really; I have never been good at it.
 Answer: **CAN'T TELL** Explanation: The statement does not contain the words ``USEFUL'' or ``USE''.

 Example 4: I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.
 Answer: **CAN'T TELL** Explanation: The statement contains the word ``USEFUL'', but also says that the they are ``not sure'' which is not only positive or only negative.

 Here is another student statement. Tell me if the statement should be categorized as USEFUL, NOT USEFUL, or CAN'T TELL. Provide your answer first and then explain your reasoning.
Statement: ``No because I don't like math''
 Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and expresses the student's
The stripped answer is:
NOT USEFUL


7
The full output is:
I asked students if they thought physics was interesting and/or useful. Help me analyze their responses to figure out which students think its USEFUL and how many think it is NOT USEFUL.
 For each student statement, first report if the student answers the question about USE.
 Only if the statement contains the word USE or USEFUL, decide if the student thinks physics is USEFUL, NOT USEFUL, or you CAN'T TELL.
 If the statement does not contain the word USE or USEFUL, you must label the statement as CAN'T TELL. Here are some examples:

 Example 1: I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.
 Answer: **USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a positive about its use.

 Example 2: I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting.
 Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a negative about its use.

 Example 3: Not really; I have never been good at it.
 Answer: **CAN'T TELL** Explanation: The statement does not contain the words ``USEFUL'' or ``USE''.

 Example 4: I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.
 Answer: **CAN'T TELL** Explanation: The statement contains the word ``USEFUL'', but also says that the they are ``not sure'' which is not only positive or only negative.

 Here is another student statement. Tell me if the statement should be categorized as USEFUL, NOT USEFUL, or CAN'T TELL. Provide your answer first and then explain your reasoning.
Statement: ``I expect learning about physics will be interesting for certain subjects. I find the mechanics of force and gravity to be especially interesting at it relates to astronomy. I'm not sure how useful physics could be in other areas of my interests, since my main career path of health management does not involve physics that much.''
Answer: **CAN'T TELL**
Explanation: The statement contains the word “USEFUL” but includes a caveat
The stripped answer is:
CAN'T TELL


8
The full output is:
I asked students if they thought physics was interesting and/or useful. Help me analyze their responses to figure out which students think its USEFUL and how many think it is NOT USEFUL.
 For each student statement, first report if the student answers the question about USE.
 Only if the statement contains the word USE or USEFUL, decide if the student thinks physics is USEFUL, NOT USEFUL, or you CAN'T TELL.
 If the statement does not contain the word USE or USEFUL, you must label the statement as CAN'T TELL. Here are some examples:

 Example 1: I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.
 Answer: **USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a positive about its use.

 Example 2: I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting.
 Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a negative about its use.

 Example 3: Not really; I have never been good at it.
 Answer: **CAN'T TELL** Explanation: The statement does not contain the words ``USEFUL'' or ``USE''.

 Example 4: I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.
 Answer: **CAN'T TELL** Explanation: The statement contains the word ``USEFUL'', but also says that the they are ``not sure'' which is not only positive or only negative.

 Here is another student statement. Tell me if the statement should be categorized as USEFUL, NOT USEFUL, or CAN'T TELL. Provide your answer first and then explain your reasoning.
Statement: ``Yes, because it is necessary for my career, but also I genuinely like science and physics. The intricacies of motion and other important every day life aspects should be mandatory for everyone to know''
Answer: **USEFUL**
Explanation: The statement contains the word ``USEFUL'' and the student states that it
The stripped answer is:
USEFUL


9
The full output is:
I asked students if they thought physics was interesting and/or useful. Help me analyze their responses to figure out which students think its USEFUL and how many think it is NOT USEFUL.
 For each student statement, first report if the student answers the question about USE.
 Only if the statement contains the word USE or USEFUL, decide if the student thinks physics is USEFUL, NOT USEFUL, or you CAN'T TELL.
 If the statement does not contain the word USE or USEFUL, you must label the statement as CAN'T TELL. Here are some examples:

 Example 1: I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas.
 Answer: **USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a positive about its use.

 Example 2: I do not expect to find it to be useful because I am a biological sciences major, but perhaps it will be interesting.
 Answer: **NOT USEFUL** Explanation: The statement contains the word ``USEFUL'' and the student is a negative about its use.

 Example 3: Not really; I have never been good at it.

## **Testing: Entire Dataset that has been coded for direct comparison**

**Make a blank dataframe to fill in with the results from this run, so we can compare it to the coded data**

In [ ]:
gemmasCodes = interest[['studentID', 'Useful','Not Useful']].copy()

In [ ]:
gemmasCodes['Useful'] = 0
gemmasCodes['Not Useful'] = 0

gemmasCodes.head()

                              studentID  Useful  Not Useful
0  85ef67d0-649f-4e26-9545-1382bd4086a3       0           0
1  2d8769ee-10f4-4635-8a2e-f8e6af40abd3       0           0
2  b6b37f0b-dad5-4d8c-acbe-4a72a693eb6e       0           0
3  f8f33e36-9c73-4007-a43b-3fcf1122f2ab       0           0
4  dbb358dd-c4e8-4714-84d9-a32e477edfd8       0           0

In [ ]:
base=prompt

count_useful, count_notUseful, count_noCode, count_fuckinGemma =0,0,0,0
with torch.no_grad():
  for i in range(0,100):

      promptWithStatement=base + "``" + interest.iloc[i]['questionStem'] + "''"
      inputs = tokenizer(promptWithStatement, return_tensors="pt").to(model.device)
      # Run inference
      outputs = model.generate(**inputs, max_new_tokens=20)
      # Decode the generated response
      ans = tokenizer.batch_decode(outputs, skip_special_tokens=True)[0]
      # Define the first bit to get just Gemma's categorization
      ans_split = ans.split(interest.iloc[i]['questionStem'])[-1]
      gemmasFeelings = re.findall(r'\*\*(.*?)\*\*',ans_split)

      print("\n")
      print(i)
      # print("The full output is:")
      # print(ans)
      print("The sentence was: ")
      print(interest.iloc[i]['questionStem'])

      if len(gemmasFeelings) == 0:
          count_fuckinGemma+=1
          print("Gemma feels that it is: ")
          print(ans_split)
          continue
      else:
          print("The stripped answer is: ")
          print(gemmasFeelings[0])

      # print("Gemma's feelings 1st element: ")
      # print(gemmasFeelings[0])

      if "Useful" == gemmasFeelings[0]:
          count_useful+=1
          gemmasCodes.at[i,'Useful'] = 1
      elif "Not Useful" == gemmasFeelings[0]:
          count_notUseful+=1
          gemmasCodes.at[i,'Not Useful'] = 1
      elif "Can't Tell" == gemmasFeelings[0]:
          count_noCode+=1
      else:
          # print("The sentence was: ")
          # print(interest.iloc[i]['questionStem'])
          # print("Gemma feels that it is: ")
          # print(ans_split)
          continue

print(count_useful)
print(count_notUseful)
print(count_noCode)
print(count_fuckinGemma)

0
The sentence was:
I expect learning physics to be useful, but not very interesting. It expect that it would take a lot of problem solving and math rather than exploring theoretic and conceptual ideas
The stripped answer is:
Useful


1
The sentence was:
I expect physics to be interesting, because I like to learn about how we can predict trajectories of a ball and perform physics labs. I think it will be very useful to better understanding our environment and how the world works.
The stripped answer is:
Useful


2
The sentence was:
I think physics is both interesting and useful. It is very applicable to the real world in the healthcare sector particularly. If also provides explanation for certain biological processes.
The stripped answer is:
Useful


3
The sentence was:
I do not expect learning physics to be interesting and useful. I don't really understand the point of knowing a bunch of information about why/how things move, because it doesn't really pertain to my major. I also don't enjoy physics as a subject, so I don't see myself applying it in my life during/after the class.
The stripped answer is:
Not Useful


4
The sentence was:
I think it will be interesting but I do not think it will come up often in my future career.
The stripped answer is:
Not Useful


5
The sentence was:
Yes, as in sports medicine for animals, looking at weight distribution is important and knowing certain biomechanics in terms of orthopedics
The stripped answer is:
Useful


6
The sentence was:
Learning physics will be useful to me. I am sure that understanding physics concepts will help me get insights about biological systems,  where passion and interests are.
The stripped answer is:
Useful


7
The sentence was:
Physics is the foundation of all other sciences: chemistry, biology, etc. In other words, everything involves physics. In this way, physics is useful to me as a future physician.
The stripped answer is:
Useful


8
The sentence was:
Yes, I do. From the little that I reviewed over the summer, the content and concepts in physics seem interesting and useful within the context of daily life and medicine (eg. the use of laparoscopic instruments in surgery).
The stripped answer is:
Useful


9
The sentence was:
I think learning physics will be difficult, but also useful because it'll help me understand and connect physics to other parts of my interests.
The stripped answer is:
Useful


10
The sentence was:
I expect to find it somewhat useful and somewhat interesting. In my particular career path I don't expect it to be very useful, however I believe a basic understanding of physics will be useful in my life in general. There are some aspects of physics that interest me, although in high school I was turned off by some challenging problems.
The stripped answer is:
Useful


11
The sentence was:
Yes. I think topics such as fluid dynamics and heat transfer are very important in both daily life and in scientific research.
The stripped answer is:
Useful


12
The sentence was:
I know physics is applicable in many parts of life and biology, so I expect it will be useful, although at this point I don't know exactly what that will look like. I also don't know how interesting it will be.
The stripped answer is:
Useful


13
The sentence was:
I think physics is interesting because it governs a lot of things in my everyday life. I don't know what situations I would apply my knowledge in, though.
The stripped answer is:
Useful


14
The sentence was:
I expect it to be interesting maybe not as useful. I want to be a surgeon and I don't think physics will come up a lot.
The stripped answer is:
Not Useful


15
The sentence was:
I expect it to be demanding and useful for completing my pre-med course requirements.
The stripped answer is:
Useful


16
The sentence was:
I feel as though physics is very important for those who wish to understand the world around them, and when combined with other fields, explains many phenomena
The stripped answer is:
Useful


17
The sentence was:
I find learning physics to be useful as it has a connection to many real life phenomena such as sports, driving, and medicine. Moreover, I am excited to learn physics concepts that will help me in the medical world in terms of understanding the physiology of the human body.
The stripped answer is:
Useful


18
The sentence was:
A little bit. I like noticing it in my everyday life. However, I don't expect it to be my strong suit.
The stripped answer is:
Useful


19
The sentence was:
No because I don't like math
The stripped answer is:
Not Useful


20
The sentence was:
I expect learning about physics will be interesting for certain subjects. I find the mechanics of force and gravity to be especially interesting at it relates to astronomy. I'm not sure how useful physics could be in other areas of my interests, since my main career path of health management does not involve physics that much.
The stripped answer is:
Not Useful


21
The sentence was:
Yes, because it is necessary for my career, but also I genuinely like science and physics. The intricacies of motion and other important every day life aspects should be mandatory for everyone to know
The stripped answer is:
Useful


22
The sentence was:
Yes, both interesting and useful. I think I ask myself a lot of questions about the biological world around me that I can imagine physics may help me further my understanding. I'm excited to be able to address some of those questions with a bit more scientific insight. I think it will be interesting because it's an untouched subject area to me.
The stripped answer is:
Useful


23
The sentence was:
I expect it to be interesting, and relatively useful. I'm not sure if I'll use it in the future, but I think physics is very interesting.
The stripped answer is:
Useful


24
The sentence was:
I expect physics to be useful for the rest of my undergraduate and graduate studies. I know that physics is heavily featured on the MCAT and this course will help me prepare. In the past, I did not find physics very interesting, but I am hoping this changes!!
The stripped answer is:
Useful


25
The sentence was:
I do find learning physics to be both interesting and useful for both my own understanding of the world around me as well as for future studies as I pursue medicine. I personally believe that concepts in physics retain longer and are harder to forget than concepts in say chemistry for example.
The stripped answer is:
Useful


26
The sentence was:
I personally do not as I will likely never do it again after the class. I think basics physics is useful but nothing more than extremely basic ideas since so much relies heavily on math which most people do not learn. But I would say this about alot of classes you have to take an university.
The stripped answer is:
Not Useful


27
The sentence was:
I think that learning physics will be interesting but I am not sure how useful it'll be in the career that i want to pursue.
The stripped answer is:
Can't Tell


28
The sentence was:
I expect that some of the information will be very useful to me in the field of medicine. I think that a lot of biomedical devices and technology are based in physics. I do thing that some of the things I am learning may not be as useful such as the electromagnitism, however I have not learned this before so maybe it will be useful.
The stripped answer is:
Useful


29
The sentence was:
Yes, I often think logically in everyday life and like to think about how things work. I think taking physics will help me to further my understanding of everyday concepts.
The stripped answer is:
Useful


30
The sentence was:
I expect to find it somewhat interesting and useful. I have taken physics before and know I will not use everything I will learn. However, some topics are helpful when thinking about the world. I also find most STEM topics engaging and expect to find physics stimulating to me as someone who likes math and science.
The stripped answer is:
Useful


31
The sentence was:
I feel that learning physics will be interesting and useful. The concepts that we will learn in physics can be applied to daily life! So I think solving physics problems will be applicable in the real world.
The stripped answer is:
Useful


32
The sentence was:
Yes physics will be interesting and useful in the real world because everything we do in life uses physics application. Learning physics will help me make those connections in life when I look at a cool architecture and start thinking about how it was built.
The stripped answer is:
Useful


33
The sentence was:
I do not expect it to be interesting but I expect it to be somewhat applicable to everyday life because physics is a part of everyday life.
The stripped answer is:
Useful


34
The sentence was:
I do not expect to find learning physics to be interesting. I used to expect it in high school and I faced a disillusionment. I do expect learning physics to be very useful even though it is extremely confusing and tedious.
The stripped answer is:
Useful


35
The sentence was:
I think that physics is interesting to learn because it has many applications in real life. For me specifically, a biology major, physics shows up in relation to enzymes and protein interactions, so it is important to know and understand physics concepts..
The stripped answer is:
Useful


36
The sentence was:
I think it will be kind of interesting but not really useful because in this introductory course I doubt if I can learn anything really applicable in my biology study.
The stripped answer is:
Not Useful


37
The sentence was:
I think it will be useful and interesting! My brother is a physics major, and his interest in it piqued mine.
The stripped answer is:
Useful


38
The sentence was:
I believe that learning physics will not be very interesting, but very useful. All science is basically physics, so understanding this foundation will help me apply myself in other difficult courses. However, physics is very hard to me, so it might not be as enjoyable as I hope it to be.
The stripped answer is:
Useful


39
The sentence was:
Yes definitely, everything in this world can be explained by physics, especially movement. Since it can be applied in so many ways, it's hard to argue that it isn't useful.
The stripped answer is:
Useful


40
The sentence was:
I definitely think it will be interesting because I am naturally very curious and because of my desired career path I think it would 100% be useful.
The stripped answer is:
Useful


41
The sentence was:
I expect to find physics moderately interesting and useful. I have never been good at physics, so I dont think i have an inclination to find it interesting like other students.
The stripped answer is:
Useful


42
The sentence was:
Not really, as of right now I do not see the intersection between veterinary medicine and physics. However, I know there is a connection, and with most of the class being pre-health I hope we are taught more about physics applications in the medical field.
The stripped answer is:
Useful


43
The sentence was:
I think I will like some topics but not others. This tends to be how I feel about most subjects so I'm sure there will be parts of physics I dislike and parts that I enjoy.
The stripped answer is:
Can't Tell


44
The sentence was:
I study architecture and I think some concepts in physics would be very useful when it comes to architecture.
The stripped answer is:
Useful


45
The sentence was:
I expect physics to be useful as it can be seen in everyday life. I think this will help to make the content more interesting. Moreover, I hope to see its applications in my major.
The stripped answer is:
Useful


46
The sentence was:
I find some topics in physics to be interesting and I know that all the topics are universally useful. I find the topics that I am constantly surrounded with and am reminded of to be interesting because you never really notice it until you learn about it.
The stripped answer is:
Useful


47
The sentence was:
Interesting because physics is everywhere. I want to understand certain aspects of physics that I see in my daily life.
The stripped answer is:
Useful


48
The sentence was:
Yes. I like math and computational methods, so I expect it to be interesting. I am not sure how directly useful to biology I expect the course to be.
The stripped answer is:
Can't Tell


49
The sentence was:
Yes, I expect to find it interesting and useful. This is because physics is a field of science where we can see its mechanisms in the real world, so learning about it wouldn't just be about theoretical ideas.
The stripped answer is:
Useful


50
The sentence was:
I do expect it to be interesting. I may not use every thing I learn precisely in my day to day life, but I feel much better knowing these things as an educated citizen.
The stripped answer is:
Useful


51
The sentence was:
Not really; I have never been good at it.
Gemma feels that it is:
''
 Answer:
 Reasoning:








52
The sentence was:
I can't guarantee it must be interesting, but I think it will surely be useful, as the microscopic part is highly associated with chemistry (e.g.electrons, protons, Œ± and Œ≤ particles)
The stripped answer is:
Useful


53
The sentence was:
I really do expect it to be interesting and useful. I am a very curious person and am interested to learn about applications toward the real world. I also am curious to see how I can use physics to learn more about human biology, my major.
The stripped answer is:
Useful


54
The sentence was:
I don't necessarily expect it to be useful to what I want to do in the future. I mainly find water physics interesting because I am a swimmer, but otherwise not much of physics sounds interesting.
The stripped answer is:
Not Useful


55
The sentence was:
I do not‚ÄîI do not believe physics will have any real-world application or relevance to my chosen field of work. I also am generally not interested in physics-related topics.
The stripped answer is:
Not Useful


56
The sentence was:
I do think physics will be interesting and useful. I like problem solving with numbers which is essentially what physics is and there are applications in everything.
The stripped answer is:
Useful


57
The sentence was:
I do expect it to be interesting. I think I will find labs to be more interesting than practice problems. I think it is useful to apply to the real world and that it can teach you important concepts to think about in everyday life.
The stripped answer is:
Useful


58
The sentence was:
I find learning physics to be interesting because I care about the laws that underlie all physical processes. I have yet to learn of a very direct link between biology (my field) and physics, but I am hopeful to discover this as the semester progresses.
The stripped answer is:
Useful


59
The sentence was:
I do! I love philosophy, and even though physics isn't super philosophical, a lot of physics was developed because of philosophical questions. I like the fact that we can ask these questions and test them in real time, observing the way that the world works around us.
The stripped answer is:
Useful


60
The sentence was:
I think I will find it interesting and useful to apply in certain aspects of my life. It might be hard now to rationalize the ways physics impacts the world, but I believe there are probably underlying principles of physics in our everyday lives.
The stripped answer is:
Useful


61
The sentence was:
I don't, I haven't enjoyed it previously
The stripped answer is:
Not Useful


62
The sentence was:
Yes, I expect physics to be interesting and useful because it is an essential science that everyone should have a foundational understanding of. Also, it helps with problem solving and that is a key skill to acquire for academics.
The stripped answer is:
Useful


63
The sentence was:
Yes, because sometimes I use my physics knowledge in physical activities, and I believe that the mechanics learned in this class will further help me in daily physical tasks.
The stripped answer is:
Useful


64
The sentence was:
Yes, I hope to pursue a research career, and I know having at the very least an introductory background in physics can be very helpful for part of that career.
The stripped answer is:
Useful


65
The sentence was:
I am not sure yet. I don't think that it is super applicable to my career path but maybe it will be once I learn more.
The stripped answer is:
Can't Tell


66
The sentence was:
Yes. Although we do not think about it on a daily basis, physics is included in many activities that we do. For example, the force of your pen when you drop it on the ground. I guess understanding the mechanism behind this can be interesting and useful in certain situations.
The stripped answer is:
Useful


67
The sentence was:
I expect physics to be interesting and useful. I have trouble keeping interest when physics problems get very hard, but the concepts themselves I find very interesting and makes me look at daily life through a different perspective.
The stripped answer is:
Useful


68
The sentence was:
I do expect to find learning physics interesting and useful. I had enjoyed it in high school and all sciences fascinate me, although I do not think it will become something I am passionate about. I think a year of learning it will make me respect/admire it much more.
The stripped answer is:
Useful


69
The sentence was:
I believe that learning physics will be both interesting and useful. Learning physics will be interesting because it is something so connected to everyday life! Investigating the laws behind why objects behave the way they do, in my eyes, is pretty cool. That being said, understanding the laws that explain why objects behave the way they do will also be useful to my everyday knowledge of why things are the way that they are, and I am confident the concepts that I learn in this physics course will be applied within my field of study.
The stripped answer is:
Useful


70
The sentence was:
It is useful for everyday applications
The stripped answer is:
Useful


71
The sentence was:
Yes. I've always had a fascination with physics through nonfiction books and YouTube channels such as Veritasium. I hope to uncover a more thorough understanding of it through this course. I have a slight interest in astronomy and quantum physics. I know that mechanics will not be close to covering those concepts, but it will provide the foundation for those more advanced concepts. Again, this will help me with my career as a future physician, so it will definitely be useful to me.
The stripped answer is:
Useful


72
The sentence was:
I expect to enjoy learning physics concepts, but also know that I will have to push myself to do problems and really understand what is going on.
The stripped answer is:
Useful


73
The sentence was:
To be honest, I don't find physics very appealing. I was never very interested in it mainly because I don't think it will be useful for my future career. I plan to go on to medical school and become a surgeon. Although physics is required for this field, I don't see how physics can be used to help patients all that much. Despite this, I will keep an open mind throughout the course.
The stripped answer is:
Not Useful


74
The sentence was:
I expect to find learning physics interesting because I will get to learn how things work.
The stripped answer is:
Useful


75
The sentence was:
I do expect it to be interesting because I tend to enjoy physics and math problems. I don't know how usefult it will be.
The stripped answer is:
Can't Tell


76
The sentence was:
I expect it to be a useful subject even if I am not necessarily interested in it.
The stripped answer is:
Useful


77
The sentence was:
Yes, I hope to find physics interesting and useful since I am a figure skater so inertia, torque, momentum all play important roles in the sport.
The stripped answer is:
Useful


78
The sentence was:

In [ ]:
gemmasCodes

                                studentID  Useful  Not Useful
0    85ef67d0-649f-4e26-9545-1382bd4086a3       1           0
1    2d8769ee-10f4-4635-8a2e-f8e6af40abd3       1           0
2    b6b37f0b-dad5-4d8c-acbe-4a72a693eb6e       1           0
3    f8f33e36-9c73-4007-a43b-3fcf1122f2ab       1           1
4    dbb358dd-c4e8-4714-84d9-a32e477edfd8       0           1
..                                    ...     ...         ...
667  d919df7f-ae2e-486f-b563-8d7780fbc994       0           0
668  b4e7cbfc-8d41-4e31-b841-89b8dbf1d0ba       0           0
669  35f501b0-2ac2-4666-bd69-aa71af516978       0           0
670  882ec822-d244-482f-9fea-b2abba2f1643       0           0
671  d930c69c-7918-478e-89cf-63ff7e9f7276       0           0

[672 rows x 3 columns]

In [ ]:
gemmasCodes.to_csv('gemmasCodes_Interest_First100.csv', index=False)